import 'dart:async';

import 'ai_service.dart';

///--------------------------------------------------
/// GEMINI SERVICE
///--------------------------------------------------
///
/// Current Version:
/// Mock implementation.
///
/// Future Version:
/// Google Gemini API integration.
///
/// StudioController communicates through AIService,
/// never directly with Gemini.
///--------------------------------------------------

class GeminiService implements AIService {
  //--------------------------------------------------
  // PROMPT ENHANCEMENT
  //--------------------------------------------------

  @override
  Future<String> enhancePrompt(
    String prompt,
  ) async {
    await Future.delayed(
      const Duration(seconds: 2),
    );

    return """
$prompt

Cinematic lighting,
Ultra realistic,
8K,
Professional color grading,
Dynamic camera movement,
Highly detailed,
Pixar-quality animation.
""";
  }

  //--------------------------------------------------
  // PROMPT REWRITE
  //--------------------------------------------------

  @override
  Future<String> rewritePrompt(
    String prompt,
  ) async {
    await Future.delayed(
      const Duration(seconds: 2),
    );

    return """
Rewrite professionally:

$prompt
""";
  }

  //--------------------------------------------------
  // STORYBOARD
  //--------------------------------------------------

  @override
  Future<List<String>> generateStoryboard(
    String prompt,
  ) async {
    await Future.delayed(
      const Duration(seconds: 2),
    );

    return [
      "Scene 1 — Opening Shot",
      "Scene 2 — Character Introduction",
      "Scene 3 — Conflict",
      "Scene 4 — Resolution",
    ];
  }

  //--------------------------------------------------
  // SCRIPT
  //--------------------------------------------------

  @override
  Future<String> generateScript(
    String prompt,
  ) async {
    await Future.delayed(
      const Duration(seconds: 2),
    );

    return """
Narrator:

$prompt

(Scene script generated by Gemini)
""";
  }

  //--------------------------------------------------
  // TITLE
  //--------------------------------------------------

  @override
  Future<String> generateTitle(
    String prompt,
  ) async {
    await Future.delayed(
      const Duration(seconds: 1),
    );

    return "Untitled AI Project";
  }

  //--------------------------------------------------
  // THUMBNAIL
  //--------------------------------------------------

  @override
  Future<String> generateThumbnail(
    String prompt,
  ) async {
    await Future.delayed(
      const Duration(seconds: 2),
    );

    return "";
  }

  //--------------------------------------------------
  // MOVIE
  //--------------------------------------------------

  @override
  Future<String> generateMovie({
    required String prompt,
    required String style,
    required String language,
    required String voice,
    required String resolution,
    required String aspectRatio,
    required String duration,
  }) async {
    await Future.delayed(
      const Duration(seconds: 4),
    );

    return "movie_job_001";
  }
}